### ISSUE TITLE
Exception in callback

### ISSUE THREAD

**Issue by LEJOUI** [zacs/ha-dualmodegeneric#42]
During startup of HA I’m getting the following error in my log.
The climate entity seems to be created though. It’s a mobile hvac, so I’m not able to test all of my functions at this point since it’s stored away right now.

logs:

```
Logger: homeassistant
Source: core.py:433 
First occurred: 06:23:15 (1 occurrences) 
Last logged: 06:23:15

Error doing job: Exception in callback DualModeGenericThermostat.async_added_to_hass.<locals>._async_startup(<Event homeassistant_start[L]>) at /config/custom_components/dualmode_generic/climate.py:382
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 835, in _onetime_listener
    self._hass.async_run_job(listener, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 452, in async_run_job
    return self.async_run_hass_job(HassJob(target), *args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 433, in async_run_hass_job
    hassjob.target(*args)
TypeError: _async_startup() takes 0 positional arguments but 1 was given

```

**Comment by bbrendon** [comment]
I just tried upgrading to 2021.12 and it blew up (not this integration) so I'm back on 2021.11.

Same exact issue.

**Comment by david-kalbermatten** [comment]
Closing this issue in favor of #43.
(Sorry, saw the other one first and already commented on it)
