### ISSUE TITLE
ValueError: 'unknown' is not a valid HVACMode

### ISSUE THREAD

**Issue by mjsambol** [zacs/ha-dualmodegeneric#55]
I upgraded today from a docker-based 2022 version of HA to 2023.5.3. Immediately after the update, everything climate related seemed OK, but following the next restart I've started seeing:

Error adding entities for domain climate with platform dualmode_generic
Error while setting up dualmode_generic platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 731, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 845, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 245, in state
    return HVACMode(self.hvac_mode).value
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 'unknown' is not a valid HVACMode

And now I have no climate control whatsoever. Help!

**Comment by mjsambol** [comment]
Apologies, this was due to my mistake. I have the custom component manually installed, not via HACS, and hadn't updated to the latest version.
