### ISSUE TITLE
Platform error: climate - Exception importing custom_components.dualmode_generic.climate after installing 7f23c3 in HA Core 2024.5.5

### ISSUE THREAD

**Issue by avalero1962** [zacs/ha-dualmodegeneric#70]
After installing 7f23c3 in HA Core 2024.1.5 I get this errors for my 5 dualmode_generic climate I have installed

Platform error 'climate' from integration 'dualmode_generic' - Exception importing custom_components.dualmode_generic.climate
Platform error 'climate' from integration 'dualmode_generic' - Exception importing custom_components.dualmode_generic.climate
Platform error 'climate' from integration 'dualmode_generic' - Exception importing custom_components.dualmode_generic.climate
Platform error 'climate' from integration 'dualmode_generic' - Exception importing custom_components.dualmode_generic.climate
Platform error 'climate' from integration 'dualmode_generic' - Exception importing custom_components.dualmode_generic.climate

I get this error in logs
Logger: homeassistant.loader
Source: loader.py:842
First occurred: 14:17:59 (15 occurrences)
Last logged: 14:40:42

Unexpected exception importing platform custom_components.dualmode_generic.climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/dualmode_generic/climate.py", line 77, in <module>
    SUPPORT_TURN_ON = ClimateEntityFeature.TURN_ON
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: TURN_ON

This is one of the definition, nothing unsual: 
- platform: dualmode_generic
  name: Termostato Dual Salón
  unique_id: climate.termostato_dual_salon
  heater: switch.csuelo_radiante_valvula_z2
  cooler: switch.a_a_salon_estado
  target_sensor: sensor.ta_y_hr_salon_temperature
  enable_heat_cool: false
  min_temp: 15
  max_temp: 30
  target_temp_step: 0.1
  cold_tolerance: 0.1
  hot_tolerance: 0.1
  min_cycle_duration:
    seconds: 1
  keep_alive:
    seconds: 10

**Comment by david-kalbermatten** [comment]
HA Core 2024.1.5 is quite heavily outdated (It's not even the latest version for January...) 
Please try updating to the most recent version of Home Assistant and see if that solves the issue.
