### ISSUE TITLE
Cannot update to fbdc0eb following HA update to 2024.8

### ISSUE THREAD

**Issue by o0larrylurex0o** [zacs/ha-dualmodegeneric#72]
Hello 
Following the recent HA update to 2024.8 and HACS integration, I just got an update notification in the HA update panel

![image](https://github.com/user-attachments/assets/6d6d94bb-8f91-4847-9779-828e28e4da24)

![image](https://github.com/user-attachments/assets/cf482bc7-9d3e-490f-a89b-1e11f5c088d7)

But i cannot perform the update.
When I try I got this error message

`Failed to perform the action update/install. The version fbdc0eb for this integration can not be used with HACS.`

Thx a lot

**Comment by zacs** [comment]
Can you send whatever the error is from the logs?

**Comment by franfos** [comment]
Hi,
this is mine:

_Traceback (most recent call last):
  File "/config/custom_components/hacs/update.py", line 88, in async_install
    await self.repository.async_download_repository(ref=version or self.latest_version)
  File "/config/custom_components/hacs/repositories/base.py", line 1419, in async_download_repository
    await self._ensure_download_capabilities(ref)
  File "/config/custom_components/hacs/repositories/base.py", line 1400, in _ensure_download_capabilities
    raise HacsException(
custom_components.hacs.exceptions.HacsException: The version fbdc0eb for this integration can not be used with HACS.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2763, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2806, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 154, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 458, in async_install_with_progress
    await self.async_install(version, backup)
  File "/config/custom_components/hacs/update.py", line 90, in async_install
    raise HomeAssistantError(exception) from exception
homeassistant.exceptions.HomeAssistantError: The version fbdc0eb for this integration can not be used with HACS._

**Comment by papacrown** [comment]
Hi, I'm getting the exact same issue, here's my log error.

`
Traceback (most recent call last):
  File "/config/custom_components/hacs/update.py", line 88, in async_install
    await self.repository.async_download_repository(ref=version or self.latest_version)
  File "/config/custom_components/hacs/repositories/base.py", line 1417, in async_download_repository
    await self._ensure_download_capabilities(ref)
  File "/config/custom_components/hacs/repositories/base.py", line 1398, in _ensure_download_capabilities
    raise HacsException(
custom_components.hacs.exceptions.HacsException: The version fbdc0eb for this integration can not be used with HACS.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2761, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2804, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 996, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1068, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 154, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 458, in async_install_with_progress
    await self.async_install(version, backup)
  File "/config/custom_components/hacs/update.py", line 90, in async_install
    raise HomeAssistantError(exception) from exception
homeassistant.exceptions.HomeAssistantError: The version fbdc0eb for this integration can not be used with HACS.
`

**Comment by matzch** [comment]
![Screenshot 2024-09-23 20 31 02](https://github.com/user-attachments/assets/582ecfa5-bdff-49c5-8dd4-8061910773a8)

**Comment by FaberO42** [comment]
+1

**Comment by Uozzon** [comment]
Same for me, this is the message: 
Translation Error: The intl string context variable "services" was not provided to the string "Impossibile eseguire l'azione: {services}" The version fbdc0eb for this integration can not be used with HACS

Thanks

**Comment by david-kalbermatten** [comment]
seems like my latest pr, solved the issue for now #73
